export const RACE_SPELLS = [
  {raceName: 'Dragonborn', draconicAncestry: 'Black', spellName: 'Breath Weapon', DamageType: 'Acid', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'line', range: {width: 5, distance: 30}, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Blue', spellName: 'Breath Weapon', DamageType: 'Lightning', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'line', range: {width: 5, distance: 30}, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Brass', spellName: 'Breath Weapon', DamageType: 'Fire', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'line', range: {width: 5, distance: 30}, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Bronze', spellName: 'Breath Weapon', DamageType: 'Lightning', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'line', range: {width: 5, distance: 30}, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Copper', spellName: 'Breath Weapon', DamageType: 'Acid', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'line', range: {width: 5, distance: 30}, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Gold', spellName: 'Breath Weapon', DamageType: 'Fire', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'cone', range: 15, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Green', spellName: 'Breath Weapon', DamageType: 'Poison', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'cone', range: 15, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Red', spellName: 'Breath Weapon', DamageType: 'Fire', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'cone', range: 15, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'Silver', spellName: 'Breath Weapon', DamageType: 'Cold', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'cone', range: 15, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0},
  {raceName: 'Dragonborn', draconicAncestry: 'White', spellName: 'Breath Weapon', DamageType: 'Cold', Damage: {dice: 'd6', amount: 2}, areaOfEffect: 'cone', range: 15, saveCharacteristic: '', description: ' You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. After you use your breath weapon, you can’t use it again until you complete a short or long rest.', ingredients: '', usageUntilRest: 2, usageUntilLongRest: 0}
]

export const CLASS_SPELLS = [
  {className: 'Barbarian', spellName: 'Rage', passiveEffects: null, activeEffect: {resistance: ['bludgeoning', 'piercing', 'slashing'], advantage: 'Strength check', damage: 2, damageType: 'physical'}, level: 1, description: 'In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action.', usageUntilRest: 0, usageUntilLongRest: 2, require: null},
  {className: 'Barbarian', spellName: 'Unarmored Defence', passiveEffects: {armorClass: "+CON Modifier"}, activeEffect: {damage: null}, level: 1, description: 'While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit', usageUntilRest: 0, usageUntilLongRest: 0, require: 'No Armor'},
  {className: 'Barbarian', spellName: 'Reckless Attack', passiveEffects: null, activeEffect: {advantage: 'Strength attacks', disadvantage: '', lastsTurns: 1, damage: null}, level: 2, description: 'You throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn. ', usageUntilRest: 0, usageUntilLongRest: 0, require: ['Combat','First Attack']}
]
